openapi: 3.1.0
info:
  version: 1.4.0.20230227
  title: ACORD Messaging Library Common Objects
  description: Common objects for current AML release.
  termsOfService: https://www.acord.org/terms-of-use
  contact:
    name: ACORD
    url: http://www.acord.org
    email: memberservices@acord.org
  license:
    name: ACORD Terms of Use
    url: https://www.acord.org/terms-of-use
servers:
  - url: https://virtserver.swaggerhub.com/SteadfastTech/InsurerAPI-ST-TEST/1.4.0.20230303
    description: SwaggerHub API Auto Mocking
paths:
  /quotation/{id}:
    get:
      tags:
        - Quotation
      summary: Get quotation by id
      description: Get quotation details by id sent via Webhook
      operationId: GetQuotationById
      parameters:
        - name: id
          in: path
          description: Quotation Id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transactionFunctionCodeContent_Type'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse_Type'
        '500':
          description: Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse_Type'
components:
  securitySchemes:
    sctpUsername:
      type: apiKey
      in: header
      name: SCTP-USERNAME
    sctpPassword:
      type: apiKey
      in: header
      name: SCTP-PASSWORD
  schemas:
    transactionFunctionCodeContent_Type:
      type: string
      title: Transaction Function Code Content Type
      description: TBD
      enum:
        - AdjustmentOfDeclaration
        - AdjustmentOfDeclarationFinalization
        - AKC
        - AKP
        - ARC
        - ARP
        - ClaimInformation
        - ClaimPolicyDetails
        - ConfirmedCancellation
        - ConfirmedClosing
        - ConfirmedLapse
        - ConfirmedReinstatement
        - CoverAcceptance
        - CreateApplication
        - CreateFundMember
        - CreateFundMemberCover
        - DeclineClosing
        - DeclinedQuotation
        - DeclinedRequestForQuotation
        - DeclinePolicyOrder
        - DeclineToRenew
        - DecreaseCover
        - FirmQuotation
        - FNOL
        - FROI
        - FundInformation
        - GetCurrentCoverOnly
        - GetFullCurrentHistory
        - GetMemberDetailsAndCurrentCover
        - GetMemberDetailsAndFullCoverHistory
        - GetMemberDetailsOnly
        - GetUnderwritingResultFromUnderwritingEngine
        - IncreaseCover
        - IndicativeQuotation
        - InitialPolicyVariationApproval
        - InitialPolicyVariationDecline
        - InitialPolicyVariationRequest
        - LapseCover
        - LifeEvent
        - LodgeClaim
        - MemberInformation
        - PassApplicationToUnderwritingEngine
        - PassQuoteToUnderwritingEngine
        - POC
        - PolicyEndorsement
        - PolicyIssuance
        - Property
        - QuotationReferred
        - RaiseApplicationEvent
        - RaiseClaimEvent
        - RaiseRequirementEvent
        - ReferralRequired
        - RegulatoryAcceptanceOfAppointment
        - RegulatoryAcceptanceOfAppointmentRenewal
        - RegulatoryAcceptanceOfAppointmentTermination
        - RegulatoryAcceptanceOfNonresidentLicenseApplication
        - RegulatoryAcceptanceOfNonresidentLicenseRenewalApplication
        - RegulatoryAcceptanceOfResidentLicenseApplication
        - RegulatoryAcceptanceOfResidentLicenseRenewalApplication
        - RegulatoryDeclineOfAppointment
        - RegulatoryDeclineOfAppointmentRenewal
        - RegulatoryDeclineOfAppointmentTermination
        - RegulatoryDeclineOfNonresidentLicenseApplication
        - RegulatoryDeclineOfNonresidentLicenseRenewalApplication
        - RegulatoryDeclineOfResidentLicenseApplication
        - RegulatoryDeclineOfResidentLicenseRenewalApplication
        - RegulatoryDeferralOfAppointment
        - RegulatoryDeferralOfAppointmentRenewal
        - RegulatoryDeferralOfAppointmentTermination
        - RegulatoryDeferralOfNonresidentLicenseApplication
        - RegulatoryDeferralOfNonresidentLicenseRenewalApplication
        - RegulatoryDeferralOfResidentLicenseApplication
        - RegulatoryDeferralOfResidentLicenseRenewalApplication
        - RegulatoryNonresidentLicenseApplication
        - RegulatoryNonresidentLicenseRenewalApplication
        - RegulatoryNotificationOfAppointment
        - RegulatoryNotificationOfAppointmentRenewal
        - RegulatoryNotificationOfAppointmentTermination
        - RegulatoryResidentLicenseApplication
        - RegulatoryResidentLicenseRenewalApplication
        - RenewalInvitation
        - RequestAdditionalInformation
        - RequestForAdjustedQuotation
        - RequestForCancellation
        - RequestForClosing
        - RequestForCover
        - RequestForIllustration
        - RequestForIssuance
        - RequestForQuotation
        - RequestForReferral
        - RequestForReinstatement
        - SendAdditionalInformation
        - SROI
        - SupplyAdditonalInformation
        - TransferCover
        - UnsuccessfulQuotation
        - UpdateCover
        - UpdateRequirement
        - Vehicle
    apiError_Type:
      type: object
      title: API Error Details
      description: API Error Details
      properties:
        code:
          type: number
        message:
          type: string
    apiErrorResponse_Type:
      type: object
      title: API Error Response
      description: API Error Response
      properties:
        error:
          $ref: '#/components/schemas/apiError_Type'
security:
  - sctpUsername: []
    sctpPassword: []
