openapi: 3.1.0
info:
  version: 1.4.0.20230227
  title: ACORD Messaging Library Common Objects
  description: Common objects for current AML release.
  termsOfService: https://www.acord.org/terms-of-use
  contact:
    name: ACORD
    url: http://www.acord.org
    email: memberservices@acord.org
  license:
    name: ACORD Terms of Use
    url: https://www.acord.org/terms-of-use
servers:
  - url: https://virtserver.swaggerhub.com/SteadfastTech/InsurerAPI-ST-TEST/1.4.0.20230303
    description: SwaggerHub API Auto Mocking
paths:
  /quotation/{id}:
    get:
      tags:
        - Quotation
      summary: Get quotation by id
      description: Get quotation details by id sent via Webhook
      operationId: GetQuotationById
      parameters:
        - name: id
          in: path
          description: Quotation Id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/contact_Type'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse_Type'
        '500':
          description: Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiErrorResponse_Type'
components:
  securitySchemes:
    sctpUsername:
      type: apiKey
      in: header
      name: SCTP-USERNAME
    sctpPassword:
      type: apiKey
      in: header
      name: SCTP-PASSWORD
  schemas:
    extensions_Type:
      type: object
      title: Extensions Type
      properties:
        attributes:
          type: object
          properties:
            extensionsDomain:
              type: string
    ACORDAggregate_Type:
      type: object
      title: ACORD Aggregate Type
      properties:
        attributes:
          type: object
          properties:
            key:
              type: string
        extensions:
          $ref: '#/components/schemas/extensions_Type'
    personExternalIdentifierTypeCodeContent_Type:
      type: string
      title: PersonExternalIdentifierTypeCodeContent Type
      description: TBD
      enum:
        - ABN
        - DriversLicenseId
        - GovernmentId
        - JurisdictionId
        - LocalIdentityDocument
        - NRIC
        - OtherId
        - PassportId
        - PoliceWarrantCard
        - TFN
        - ValidTravelDocument
        - VisaId
        - WorkPermitId
    personExternalIdentifier_Type:
      type: object
      title: PersonExternalIdentifier Type
      allOf:
        - $ref: '#/components/schemas/ACORDAggregate_Type'
        - required:
            - typeCode
            - id
          properties:
            typeCode:
              $ref: '#/components/schemas/personExternalIdentifierTypeCodeContent_Type'
            jurisdictionCode:
              oneOf:
                - type: object
                  required:
                    - value
                  properties:
                    value:
                      type: string
                    attributes:
                      type: object
                      properties:
                        codeListReference:
                          type: string
                - type: string
                  maxLength: 255
            sourceURI:
              type: string
              format: uri
            id:
              type: string
              maxLength: 255
            identifierDescription:
              type: string
    personNameTypeCodeContent_Type:
      type: string
      title: Person Name Type Code Content Type
      description: The type code content of the Person name
      enum:
        - Alias
        - AlsoKnownAs
        - Maiden
        - Previous
        - Primary
    personTitlePrefixCodeContent_Type:
      type: string
      title: Person Title Prefix Code Content Type
      description: TBD
      enum:
        - AdjunctProfessor
        - Admiral
        - Advocate
        - Archbishop
        - AssociateProfessor
        - Bishop
        - Brigadier
        - Captain
        - Colonel
        - Commissioner
        - Director
        - Doctor
        - Economist
        - EstateLate
        - Father
        - General
        - Honourable
        - HonourableJudge
        - Inspector
        - Judge
        - Justice
        - Lady
        - Lieutenant
        - LieutenantColonel
        - LieutenantCommander
        - Lord
        - Magistrate
        - Major
        - Minister
        - Miss
        - Mr
        - MrJnr
        - Mrs
        - MrSnr
        - Ms
        - Pastor
        - Professor
        - ProfessorEmerita
        - ProfessorEmeritus
        - Psychologist
        - Rabbi
        - RevOrReverend
        - Sergeant
        - Sir
        - Sister
        - SnrSup
        - Sup
        - TheHonourable
        - Trust
        - Trustee
        - Unknown
    personName_Type:
      type: object
      title: Person Name Type
      allOf:
        - $ref: '#/components/schemas/ACORDAggregate_Type'
        - properties:
            typeCode:
              $ref: '#/components/schemas/personNameTypeCodeContent_Type'
            indexName:
              type: string
              maxLength: 255
            fullName:
              type: string
              maxLength: 255
            surname:
              type: string
              maxLength: 255
            givenName:
              type: string
              maxLength: 255
            otherGivenName:
              type: string
              maxLength: 255
            combinedGivenNames:
              type: string
              maxLength: 255
            personTitlePrefix:
              type: string
              maxLength: 255
            personTitlePrefixCode:
              $ref: '#/components/schemas/personTitlePrefixCodeContent_Type'
            nameSuffix:
              type: string
              maxLength: 255
            nickname:
              type: string
              maxLength: 255
            initials:
              type: string
              maxLength: 255
    personReferences_Type:
      type: object
      title: PersonReference Type
      properties:
        attributes:
          type: object
          properties:
            personReference:
              type: string
        externalIdentifier:
          oneOf:
            - type: array
              items:
                $ref: '#/components/schemas/personExternalIdentifier_Type'
            - $ref: '#/components/schemas/personExternalIdentifier_Type'
        personName:
          oneOf:
            - type: array
              items:
                $ref: '#/components/schemas/personName_Type'
            - $ref: '#/components/schemas/personName_Type'
    contactRoleCodeContent_Type:
      type: string
      title: ContactRoleCodeContent Type
      description: The Contact Role Code content enumeration
      enum:
        - Authorization
        - Broker
        - ClaimContact
        - ClaimHandler
        - Insured
        - Insurer
        - LegalOfficer
        - Other
        - PreferredContact
        - PreferredInsuranceBuyingContact
        - Processor
        - Underwriter
    contactPeriod_Type:
      type: object
      title: Contact Period Type
      allOf:
        - $ref: '#/components/schemas/ACORDAggregate_Type'
        - properties:
            startDate:
              type: string
              format: date
            endDate:
              type: string
              format: date
            startTime:
              type: string
              format: time
            endTime:
              type: string
              format: time
            localStandardTimeAppliesToInceptionDateIndicator:
              type: boolean
            periodDuration:
              type: string
              format: duration
            continuousDurationIndicator:
              type: boolean
            timePeriodDescription:
              type: string
              maxLength: 255
            bothDaysInclusiveIndicator:
              type: boolean
    blackoutPeriod_Type:
      type: object
      title: Blackout Period Type
      properties:
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        startTime:
          type: string
          format: time
        endTime:
          type: string
          format: time
        localStandardTimeAppliesToInceptionDateIndicator:
          type: boolean
        periodDuration:
          type: string
          format: duration
        continuousDurationIndicator:
          type: boolean
        timePeriodDescription:
          type: string
          maxLength: 255
        bothDaysInclusiveIndicator:
          type: boolean
    communicationPreferences_Type:
      type: object
      title: Communication Preferences Type
      allOf:
        - $ref: '#/components/schemas/ACORDAggregate_Type'
        - properties:
            priorityRank:
              type: string
              pattern: ^[0-9]{1,15}$
            contactPeriod:
              $ref: '#/components/schemas/contactPeriod_Type'
            blackoutPeriod:
              $ref: '#/components/schemas/blackoutPeriod_Type'
            doNotContactIndicator:
              type: boolean
    communicationMethod_Type:
      type: object
      title: Communication Method Type
      allOf:
        - $ref: '#/components/schemas/ACORDAggregate_Type'
        - properties:
            primaryIndicator:
              type: boolean
            previousIndicator:
              type: boolean
            communicationPreferences:
              oneOf:
                - type: array
                  items:
                    $ref: '#/components/schemas/communicationPreferences_Type'
                - $ref: '#/components/schemas/communicationPreferences_Type'
    telephoneTypeCodeContent_Type:
      type: string
      title: TelephoneTypeCodeContent_Type
      description: The Telephone Code content enumeration
      enum:
        - Fax
        - InternetProtocol
        - Marine
        - Pager
        - TextTelephone
        - Unknown
        - Wired
        - Wireless
    telephone_Type:
      type: object
      title: Telephone Type
      allOf:
        - $ref: '#/components/schemas/communicationMethod_Type'
        - required:
            - typeCode
          properties:
            typeCode:
              $ref: '#/components/schemas/telephoneTypeCodeContent_Type'
            dayIndicator:
              type: boolean
            eveningIndicator:
              type: boolean
            asOfDate:
              type: string
              format: date
            phoneNumber:
              type: string
              minLength: 1
              maxLength: 32
              pattern: \+\S+\-\S+\-\S+(\+\S+)?
            phoneNumberUnformatted:
              type: string
    emailTypeCodeContent_Type:
      type: string
      title: EmailTypeCodeContent_Type
      description: The Email Code content enumeration
      enum:
        - Business
        - Personal
        - Unknown
    email_Type:
      type: object
      title: Email Type
      allOf:
        - $ref: '#/components/schemas/communicationMethod_Type'
        - properties:
            typeCode:
              $ref: '#/components/schemas/emailTypeCodeContent_Type'
            emailAddress:
              type: string
              maxLength: 255
            asOfDate:
              type: string
              format: date
    addressReferences_Type:
      type: object
      title: Address References Type
      allOf:
        - $ref: '#/components/schemas/ACORDAggregate_Type'
        - properties:
            attributes:
              type: object
              properties:
                addressReference:
                  type: string
    coreRoleCodeContent_Type:
      type: string
      title: CoreRoleCodeContent_Type
      description: The Core Role Code content enumeration
      enum:
        - Agency
        - Broker
        - Bureau
        - ClaimAdministrator
        - Customer
        - DataCollectionAgency
        - EmployeeSecurityId
        - Employer
        - FundOrganization
        - Insured
        - Insurer
        - Jurisdiction
        - ManagingGeneralAgent
        - PlacingExchange
        - Police
        - PostalAuthority
        - PremiumFinanceCompany
        - Producer
        - ProducerLicensingAppointmentExchange
        - RegulatoryAgency
        - ServiceProvider
        - ThirdPartyAdministrator
        - ThirdPartyEntity
        - Underwriter
    assignedIdentifier_Type:
      type: object
      title: Assigned Identifier Type
      required:
        - roleCode
        - id
      properties:
        roleCode:
          $ref: '#/components/schemas/coreRoleCodeContent_Type'
        id:
          type: string
        identifierDescription:
          type: string
    contactAddress_Type:
      type: object
      title: Contact Address Type
      allOf:
        - $ref: '#/components/schemas/communicationMethod_Type'
        - properties:
            attentionName:
              type: string
              maxLength: 255
            asOfDate:
              type: string
              format: date
            addressReferences:
              $ref: '#/components/schemas/addressReferences_Type'
            assignedIdentifier:
              oneOf:
                - type: array
                  items:
                    $ref: '#/components/schemas/assignedIdentifier_Type'
                - $ref: '#/components/schemas/assignedIdentifier_Type'
    mailingAddressExternalIdentifierTypeCodeContent_Type:
      type: string
      title: MailingAddressExternalIdentifierTypeCodeContent Type
      description: TBD
      enum:
        - PostalAuthority
    mailingAddressExternalIdentifier_Type:
      type: object
      title: MailingAddressExternalIdentifier Type
      allOf:
        - $ref: '#/components/schemas/ACORDAggregate_Type'
        - required:
            - typeCode
            - id
          properties:
            typeCode:
              $ref: '#/components/schemas/mailingAddressExternalIdentifierTypeCodeContent_Type'
            jurisdictionCode:
              oneOf:
                - type: object
                  required:
                    - value
                  properties:
                    value:
                      type: string
                    attributes:
                      type: object
                      properties:
                        codeListReference:
                          type: string
                - type: string
                  maxLength: 255
            sourceURI:
              type: string
              format: uri
            id:
              type: string
              maxLength: 255
            identifierDescription:
              type: string
    mailingAddress_Type:
      type: object
      title: Mailing Address Type
      allOf:
        - $ref: '#/components/schemas/contactAddress_Type'
        - properties:
            externalIdentifier:
              oneOf:
                - type: array
                  items:
                    $ref: '#/components/schemas/mailingAddressExternalIdentifier_Type'
                - $ref: '#/components/schemas/mailingAddressExternalIdentifier_Type'
            postalBarcode:
              type: string
            postalBarcodeSortPlan:
              type: string
            postalNationalSortPlan:
              type: string
    contact_Type:
      type: object
      title: Contact Type
      allOf:
        - $ref: '#/components/schemas/ACORDAggregate_Type'
        - properties:
            personReferences:
              $ref: '#/components/schemas/personReferences_Type'
            roleCode:
              $ref: '#/components/schemas/contactRoleCodeContent_Type'
            telephone:
              oneOf:
                - type: array
                  items:
                    $ref: '#/components/schemas/telephone_Type'
                - $ref: '#/components/schemas/telephone_Type'
            email:
              oneOf:
                - type: array
                  items:
                    $ref: '#/components/schemas/email_Type'
                - $ref: '#/components/schemas/email_Type'
            mailingAddress:
              $ref: '#/components/schemas/mailingAddress_Type'
    apiError_Type:
      type: object
      title: API Error Details
      description: API Error Details
      properties:
        code:
          type: number
        message:
          type: string
    apiErrorResponse_Type:
      type: object
      title: API Error Response
      description: API Error Response
      properties:
        error:
          $ref: '#/components/schemas/apiError_Type'
security:
  - sctpUsername: []
    sctpPassword: []
